services:
  api:
    build: .
    container_name: devnagrifarms_api
    ports:
      - "80:8080"
    restart: always
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-region: "ap-south-1"
        awslogs-group: "/ec2/devnagrifarms-staging-backend"
        awslogs-stream: "backend"
